### ISSUE TITLE
SUGGESTION: The cost of collaboration for code and art

### ISSUE THREAD

**Issue by jdittrich** [victoria-bondarchuk/List-of-Academic-Research-on-Usability-in-FOSS#2]
It is not exactly FOSS+Usability, but on collaborating on code and arts/design:

Hill, Benjamin Mako, and Andrés Monroy-Hernández. **"The cost of collaboration for code and art: evidence from a remixing community."** Proceedings of the 2013 conference on Computer supported cooperative work. *ACM, 2013.* [The cost of coll… on arxiv](https://arxiv.org/pdf/1507.01297.pdf)

**Comment by victoria-bondarchuk** [comment]
@jdittrich Thank you for sharing, interesting paper which is very much on the point how to make non-code and code contributers work together in order to improve softfare. I will add it next week or you are more than welcome to submit a PR ;)
