### ISSUE TITLE
Usability in Free Software thesis

### ISSUE THREAD

**Issue by jancborchardt** [victoria-bondarchuk/List-of-Academic-Research-on-Usability-in-FOSS#4]
Not sure if my thesis counts as academic research? ;) http://jancborchardt.net/usability-in-free-software or would it need to be published in a paper of some sort? @victoria-bondarchuk

**Comment by jdittrich** [comment]
I would assume your thesis, as well as my book would be a bit unusual there – most are based on empirical studies, reported in detail (I know that both you and I worked empirically but both of our works don't focus on our methods a lot). 
However, we also have "Why Free Software has poor usability, and how to improve it" by MPT in the list, which is "just" a good blogpost.

**Comment by jancborchardt** [comment]
> However, we also have "Why Free Software has poor usability, and how to improve it" by MPT in the list, which is "just" a good blogpost.

@jdittrich yeah, that’s why I was thinking … since there is not much academic work in the  field, where to draw the line. :)

**Comment by victoria-bondarchuk** [comment]
Thank you for bringing it up, @jancborchardt and @jdittrich! I added your work to the list! 
I believe it will benefit anyone interested in the subject of usability and culture in open and free software! 
If you remember more materials please contribute!

**Comment by jancborchardt** [comment]
@victoria-bondarchuk cool! Just a detail, my thesis is from 2011, not 2012. :)

Also, in the type of "well-written blog post / essay" goes the great "Free Software UI" by Havoc Pennington:
http://ometer.com/free-software-ui.html

It includes a piece on Preferences which I refer to again and again (I think Allan Day from GNOME as well :)

**Comment by victoria-bondarchuk** [comment]
@jancborchardt fixed, I looked at internet archive to see when you uploaded them to website ))
